export default function Head() {
   return (
      <>
         <title>World Wide Weeb</title>
         <meta content="width=device-width, initial-scale=1" name="viewport" />
         <meta
            name="Provides details about the anime and manga"
            content="Generated by create next app"
         />
         <link rel="icon" href="favicon.svg" />
      </>
   );
}
